repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 2.2.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements-dev.txt", "--with", "dev", "--without-hashes"]
      - id: poetry-install
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy